---
- name: Check if address-controller secret exists
  shell: oc get secret -n {{ namespace }} address-controller-cert
  register: secret_exists
  ignore_errors: True
- name: Create temp folder for address controller certificates
  when: secret_exists.failed
  register: cert_temp
  tempfile:
    state: directory
- name: Create private key for address controller certificate
  when: secret_exists.failed
  openssl_privatekey:
    path: "{{ cert_temp.path }}/tls.key"
- name: Create a certificate signing request for address controller
  when: secret_exists.failed
  openssl_csr:
    path: "{{ cert_temp.path }}/tls.csr"
    common_name: address-controller.{{ namespace }}.svc.cluster.local
    organization_name: enmasse.io
    privatekey_path: "{{ cert_temp.path }}/tls.key"
- name: Create a signed certificate to use for the address controller
  when: secret_exists.failed
  openssl_certificate:
    path: "{{ cert_temp.path }}/tls.crt"
    privatekey_path: "{{ cert_temp.path }}/tls.key"
    csr_path: "{{ cert_temp.path }}/tls.csr"
    provider: selfsigned
- name: Create a secret containing the address-controller certificate
  shell: oc create secret tls address-controller-cert -n {{ namespace }} --cert="{{ cert_temp.path }}/tls.crt" --key="{{ cert_temp.path }}/tls.key"
  when: secret_exists.failed
- name: Check if enmasse-admin SA exists
  shell: oc get sa enmasse-admin
  register: sa_exists
  ignore_errors: True
- name: Create enmasse-admin SA
  shell: oc create sa enmasse-admin -n {{ namespace }}
  when: sa_exists.failed
- name: Check if address-space-admin SA exists
  shell: oc get sa address-space-admin
  register: sa_exists
  ignore_errors: True
  when: not multitenant
- name: Create address space admin SA
  shell: oc create sa address-space-admin -n {{ namespace }}
  when: not multitenant and sa_exists.failed
- name: Grant view policy to default SA
  shell: oc policy add-role-to-user view system:serviceaccount:{{ namespace }}:default
  when: not multitenant
- name: Grant admin policy to enmasse-admin
  shell: oc policy add-role-to-user admin system:serviceaccount:{{ namespace }}:enmasse-admin
  when: not multitenant
- name: Grant admin policy to address-space-admin
  shell: oc policy add-role-to-user admin system:serviceaccount:{{ namespace }}:address-space-admin
  when: not multitenant
- name: Create cluster wide roles used by enmasse-admin service account
  shell: oc apply -n {{ namespace }} -f {{ playbook_dir }}/templates/cluster-roles.yaml
  when: multitenant
- name: Grant cluster admin privileges to service account
  shell: oc adm policy add-cluster-role-to-user enmasse-namespace-admin system:serviceaccount:{{ namespace }}:enmasse-admin
  when: multitenant
- name: Deploy standard address space plans
  shell: oc apply -f {{ playbook_dir }}/templates/addons/standard-plans.yaml
- name: Deploy brokered address space plans
  shell: oc apply -f {{ playbook_dir }}/templates/addons/brokered-plans.yaml
- name: Deploy default address space
  shell: oc process -f {{ playbook_dir }}/templates/address-space.yaml NAME=default NAMESPACE={{ namespace }} TYPE=standard PLAN=unlimited-standard | oc apply -n {{ namespace }} -f -
  when: not multitenant
- name: Deploy the address controller
  shell: oc process -f {{ playbook_dir }}/templates/enmasse.yaml ENABLE_RBAC={{ enable_rbac }} ADDRESS_CONTROLLER_CERT_SECRET=address-controller-cert | oc apply -n {{ namespace }} -f -


